export const USERS = [
  {
    gender: "male",
    title: "Mr",
    first: "John",
    last: "Doe",
    email: "johndoe@gmail.com",
    username: "john_doe",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    gender: "female",
    title: "Ms",
    first: "Jane",
    last: "Smith",
    email: "janesmith@gmail.com",
    username: "jane_smith",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    gender: "male",
    title: "Mr",
    first: "Michael",
    last: "Brown",
    email: "michaelbrown@gmail.com",
    username: "michael_brown",
    image: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    gender: "female",
    title: "Ms",
    first: "Emily",
    last: "Wilson",
    email: "emilywilson@gmail.com",
    username: "emily_wilson",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    gender: "male",
    title: "Mr",
    first: "David",
    last: "Taylor",
    email: "davidtaylor@gmail.com",
    username: "david_taylor",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    gender: "female",
    title: "Ms",
    first: "Sarah",
    last: "Anderson",
    email: "sarahanderson@gmail.com",
    username: "sarah_anderson",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    gender: "male",
    title: "Mr",
    first: "Daniel",
    last: "Thomas",
    email: "danielthomas@gmail.com",
    username: "daniel_thomas",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    gender: "female",
    title: "Ms",
    first: "Olivia",
    last: "Jackson",
    email: "oliviajackson@gmail.com",
    username: "olivia_jackson",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    gender: "male",
    title: "Mr",
    first: "James",
    last: "White",
    email: "jameswhite@gmail.com",
    username: "james_white",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    gender: "female",
    title: "Ms",
    first: "Sophia",
    last: "Harris",
    email: "sophiaharris@gmail.com",
    username: "sophia_harris",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    gender: "male",
    title: "Mr",
    first: "Chris",
    last: "Martin",
    email: "chrismartin@gmail.com",
    username: "chris_martin",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    gender: "female",
    title: "Ms",
    first: "Isabella",
    last: "Thompson",
    email: "isabellathompson@gmail.com",
    username: "isabella_thompson",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    gender: "male",
    title: "Mr",
    first: "Matthew",
    last: "Garcia",
    email: "matthewgarcia@gmail.com",
    username: "matthew_garcia",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    gender: "female",
    title: "Ms",
    first: "Mia",
    last: "Martinez",
    email: "miamartinez@gmail.com",
    username: "mia_martinez",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    gender: "male",
    title: "Mr",
    first: "Andrew",
    last: "Robinson",
    email: "andrewrobinson@gmail.com",
    username: "andrew_robinson",
    image: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    gender: "female",
    title: "Ms",
    first: "Charlotte",
    last: "Clark",
    email: "charlotteclark@gmail.com",
    username: "charlotte_clark",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    gender: "male",
    title: "Mr",
    first: "Joseph",
    last: "Rodriguez",
    email: "josephrodriguez@gmail.com",
    username: "joseph_rodriguez",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    gender: "female",
    title: "Ms",
    first: "Amelia",
    last: "Lewis",
    email: "amelialewis@gmail.com",
    username: "amelia_lewis",
    image: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    gender: "male",
    title: "Mr",
    first: "Ethan",
    last: "Lee",
    email: "ethanlee@gmail.com",
    username: "ethan_lee",
    image: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    gender: "female",
    title: "Ms",
    first: "Harper",
    last: "Walker",
    email: "harperwalker@gmail.com",
    username: "harper_walker",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
  },
] as const;

export function getRandomUser() {
  const randomIndex = Math.floor(Math.random() * USERS.length);
  const template = USERS[randomIndex];

  const age = Math.floor(Math.random() * 81) + 10; // 10–90

  return {
    name: {
      title: template.title,
      first: template.first,
      last: template.last,
    },
    email: template.email,
    picture: template.image,
    gender: template.gender,
    login: {
      username: template.username,
    },
    dob: {
      age,
    },
  };
}
